apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mega-kubernetes-application
  # region: eu-central-1

nodeGroups:
  - name: linux-nodes
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
