apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: v-dynamic-statefulset
spec:
  serviceName: "v-dynamic-headless"
  replicas: 2
  selector:
    matchLabels:
      app: v-dynamic-nginx
  template:
    metadata:
      labels:
        app: v-dynamic-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.26.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /yep
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Mi
        storageClassName: "standard"
---
apiVersion: v1
kind: Service
metadata:
  name: v-dynamic-headless
spec:
  clusterIP: None
  selector:
    app: v-dynamic-nginx
