apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-deamonset
  namespace: working-namespace
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd-container
          image: fluentd:v1.16-1
