apiVersion: batch/v1
kind: Job
metadata:
  name: echo-date-minimal
spec:
  template:
    spec:
      containers:
        - name: ehco
          image: busybox:1.36.1
          command: ["date"]
      restartPolicy: Never
  backoffLimit: 1
