apiVersion: v1
kind: PersistentVolume
metadata:
  name: v-manual-pv
  labels:
    name: v-manual-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: standard
  local:
    path: /yep # path in the container
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube # node name
