apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: v-manual-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      name: v-manual-pv # persistent volume label
  storageClassName: standard
